Include <string>.
Without this change, building simx with clang-600.0.54 (Xcode 6.1) and
boost 1.56.0 on MacOS 10.9.5 fails for me:

src/simx/Global/OptionMap.C:46:41: error: implicit instantiation of undefined
      template 'std::__1::basic_string<char, std::__1::char_traits<char>,
      std::__1::allocator<char> >'
  bool OptionMap_::Register(std::string name, OptionHandler func)
                                        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:188:33: note:
      template is declared here
    class _LIBCPP_TYPE_VIS_ONLY basic_string;
                                ^